language: cpp

env:
    - SHARED=off
    - SHARED=on

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gfortran openmpi-bin libhdf5-openmpi-dev doxygen graphviz libboost-all-dev

install:
    - mkdir build
    - cd build
    - cmake
        -DBUILD_DOCUMENTATION=ON
        -DTEST=ON
        -DBUILD_SHARED_LIBS=$SHARED
        -DCMAKE_Fortran_COMPILER=mpif90
        -DCMAKE_BUILD_TYPE=Debug
        ..
    - make
    - make doc

script:
    - make test ARGS='-V --output-on-failure'
    - if git --no-pager grep --color -n --full-name '[ 	]$' -- CMakeLists.txt \*.[fF] \*.[fF]90 \*.c \*.cpp \*.h; then
        echo "ERROR - Trailing whitespace found in source file(s)";
        exit 1;
      fi
