language: c

env:
    - SHARED=off
    - SHARED=on

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gfortran openmpi-bin libhdf5-openmpi-dev doxygen graphviz

install:
    - mkdir build
    - cd build
    - cmake
        -DBUILD_DOCUMENTATION=ON
        -DTEST=ON
        -DBUILD_SHARED_LIBS=$SHARED
        -DCMAKE_Fortran_COMPILER=mpif90
        ..
    - make
    - make doc

script:
    - make test ARGS='-V --output-on-failure'
