language: cpp

sudo: false

addons:
  apt:
    packages:
      - &required
        - gfortran
        - doxygen
        - graphviz
        - libboost-all-dev
      - &openmpi
        - openmpi-bin
        - libhdf5-openmpi-dev
      - &mpich
        - mpich-bin
        - libhdf5-mpich-dev
      - &lam
        - lam-runtime
        - libhdf5-lam-dev

matrix:
  include:
    - env: SHARED=off
      addons: { apt: { packages: [ *required, *openmpi ] } }
    - env: SHARED=off
      addons: { apt: { packages: [ *required, *mpich ] } }
    - env: SHARED=off
      addons: { apt: { packages: [ *required, *lam ] } }
    - env: SHARED=on
      addons: { apt: { packages: [ *required, *openmpi ] } }
    - env: SHARED=on
      addons: { apt: { packages: [ *required, *mpich ] } }
    - env: SHARED=on
      addons: { apt: { packages: [ *required, *lam ] } }

install:
    - mkdir build
    - cd build
    - cmake
        -DBUILD_DOCUMENTATION=ON
        -DTEST=ON
        -DBUILD_SHARED_LIBS=$SHARED
        -DCMAKE_Fortran_COMPILER=mpif90
        ..
    - make
    - make doc

script:
    - make test ARGS='-V --output-on-failure'
